version: '3.6'

services:
  nginx:
    env_file:
      - ./env/.vhost.env
    volumes:
      - ./data/nginx:/data/nginx
    networks:
      - app-front-tier
      - reverse-proxy
    restart: unless-stopped

  nodebb:
    volumes:
      - ./data/nodebb:/mnt/data/nodebb
    working_dir: /app
    entrypoint: ./nodebb
    command: [start]
    expose:
      - "4567"
    networks:
      - app-front-tier
      - app-back-tier
    restart: unless-stopped

  redis:
    env_file:
      - env/.redis.env
    volumes:
      - ./data/redis:/data
    sysctls:
      - net.core.somaxconn=511
    networks:
      - app-back-tier
    restart: unless-stopped

  sshd:
    ports:
      - "${SSHD_PUBLIC_PORT}:22"
    networks:
      - app-back-tier
    restart: unless-stopped

networks:
  app-front-tier:
  app-back-tier:
  reverse-proxy:
    external:
      name: reverse-proxy
